version: 2
jobs:
  build:
    working_directory: ~/FlowKit
    docker:
      - image: circleci/android:api-22-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
path: app/build/test-results
